# Generated by Django 4.2.15 on 2024-09-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_fav_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itemsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.items'),
        ),
    ]
