# Generated by Django 4.2.15 on 2024-09-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_cart_itemsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itemsid',
            field=models.IntegerField(),
        ),
    ]
