# Generated by Django 4.2.15 on 2024-09-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_alter_items_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
    ]
